export const CardArray = (props) => [
  {
    id: 1,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 2,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 3,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 4,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 5,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 6,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 7,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 8,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 9,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
  {
    id: 10,
    title: "#I am into men",
    posts: [
      { id: 1, username: "homer", post: { content: "I love bananas" } },
      { id: 1, username: "homie", post: { content: "I love bananas too" } },
      { id: 3, username: "holmes", post: { content: "me too" } },
      { id: 4, username: "beff", post: { content: "I love bananas" } },
      { id: 5, username: "jezzos", post: { content: "I love bananas" } },
      { id: 6, username: "ninki", post: { content: "my anaconda" } },
      { id: 7, username: "minjaz", post: { content: "I love bananas" } },
    ],
  },
];
