export const CardArray = (props) => [
  {
    id: 1,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 2,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 3,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 4,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 5,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 6,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 7,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 8,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 9,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
  {
    id: 10,
    title: "#I am into men",
    posts: [
      {
        id: 1,
        userpic: require("../assets/mountain.jpg"),
        username: "homer",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 2,
        userpic: require("../assets/mountain.jpg"),
        username: "homie",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas too",
        },
      },
      {
        id: 3,
        userpic: require("../assets/mountain.jpg"),
        username: "holmes",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "me too",
        },
      },
      {
        id: 4,
        userpic: require("../assets/mountain.jpg"),
        username: "beff",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 5,
        userpic: require("../assets/mountain.jpg"),
        username: "jezzos",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
      {
        id: 6,
        userpic: require("../assets/mountain.jpg"),
        username: "ninki",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "my anaconda",
        },
      },
      {
        id: 7,
        userpic: require("../assets/mountain.jpg"),
        username: "minjaz",
        post: {
          id: 1,
          time: "3 hrs ago",
          reactions: { heart: 300, comment: 250 },
          comments: [
            {
              id: 1,
              username: "larry",
              content: "haha yes",
              heart: 5,
              replies: {},
            },
            {
              id: 1,
              username: "harry",
              content: "heck yea",
              heart: 3,
              replies: {},
            },
          ],
          content: "I love bananas",
        },
      },
    ],
  },
];
